### ISSUE TITLE
Wire Frame Team Review

### ISSUE THREAD

**Issue by wcollins185** [rajivjagirdar/API-Project#10]
Team to review milestone posted on Git Hub under the "wireframe" branch and provide feed back. target due date is 10/8/18

**Comment by Louis-McGruder** [comment]
What does this 'issue as a blocker' mean?

**Comment by wcollins185** [comment]
Meaning I can't move forward with finalizing the wire frame until you guys have reviewed and issued comments.

**Comment by rajivjagirdar** [comment]
I'm ok with this for now.  We obviously need to put in the form section for search, and I think that each API section needs to be separated instead of in one div.  This way we can adjust how the ajax data call displays on each section.  We also need to add in the id's and classes.
